#!/bin/bash

if [[ $# -eq 0 ]]; then
    echo "You must provide at least one Python version."
    exit 2
fi

echo "Configuring packages..."
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install -yy \
    build-essential \
    libbz2-dev \
    libffi-dev \
    libgdbm-dev \
    libgdbm-compat-dev \
    liblzma-dev \
    libncurses5-dev \
    libnss3-dev \
    libreadline6-dev \
    libssl-dev \
    libsqlite3-dev \
    pkg-config \
    tk-dev \
    wget \
    zlib1g-dev \
    gdb \
    lcov \
    lzma \
    lzma-dev \
    uuid-dev \
    make \
    gcc

cd /tmp

for VER do
    if [[ $VER == *"a"* ]]; then
        PARTIAL="$(cut -d 'a' -f 1 <<< $VER)"
    elif [[ $VER == *"b"* ]]; then
        PARTIAL="$(cut -d 'b' -f 1 <<< $VER)"
    elif [[ $VER == *"rc"* ]]; then
        PARTIAL="$(cut -d 'r' -f 1 <<< $VER)"
    else
        PARTIAL=$VER
    fi

    echo "Downloading Python $VER..."
    wget https://www.python.org/ftp/python/$PARTIAL/Python-$VER.tgz

    if [[ ! -f Python-$VER.tgz ]]; then
        echo "That Python version does not exist."
        exit 2
    fi

    tar -xvf Python-$VER.tgz

    echo "Building Python $VER..."
    cd Python-$VER
    ./configure --enable-optimizations --with-ensurepip=install
    make -j $(nproc)

    echo "Installing Python $VER..."
    sudo make altinstall
done

echo "All done!"
